# Site wide configuration

title: SurfRCaT Homepage
locale: en_US

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: Matthew P. Conlin
  bio: "This is a test."
  email: conlinm@ufl.edu

