remote_theme: christianezeani/panthera-jekyll

title: SurfRCaT Homepage

left_side:
  background_image: "/_data/icon3.png"
  
menu:
  - text: Home
    link: /
    icon: ""
    
  - text: Example Page
    link: /example
    icon: ""



